Importing Libraries

In [ ]:
from sklearn import svm, datasets
import sklearn.model_selection as model_selection
from sklearn.metrics import accuracy_score
from sklearn.metrics import f1_score
from sklearn.metrics import confusion_matrix
from sklearn import preprocessing
import numpy as np
import pandas as pd

Loading the dataset

In [ ]:
dataset = pd.read_csv('./Features_cnn.csv')
X = dataset.iloc[ : , 2 : ].values
y = dataset.iloc[ : , 0 ].values
print(X)
print(y)


Feature scaling of the dataset

In [ ]:

min_max_scaler = preprocessing.MinMaxScaler(feature_range =(0, 1))
X = min_max_scaler.fit_transform(X)
print ("\nAfter min max Scaling : \n",X)


Train test split

In [ ]:
X_train, X_test, y_train, y_test = model_selection.train_test_split(X, y, train_size=0.80, test_size=0.20, random_state=101)

Training RBF and Polynomial SVM kernels

In [ ]:
rbf = svm.SVC(kernel='rbf', gamma=.1, C=10).fit(X_train, y_train)
poly = svm.SVC(kernel='poly', degree=8, C=10).fit(X_train, y_train)

poly_pred = poly.predict(X_test)
rbf_pred = rbf.predict(X_test)

In [ ]:
poly_accuracy = accuracy_score(y_test, poly_pred)
poly_f1 = f1_score(y_test, poly_pred, average='weighted')
print('Accuracy (Polynomial Kernel): ', "%.2f" % (poly_accuracy*100))
print('F1 (Polynomial Kernel): ', "%.2f" % (poly_f1*100))
print(confusion_matrix(y_test, poly_pred))

Accuracy (Polynomial Kernel):  98.75
F1 (Polynomial Kernel):  98.75
[[74  0  0  0]
 [ 0 86  0  2]
 [ 0  0 80  0]
 [ 0  2  0 76]]


In [ ]:
rbf_accuracy = accuracy_score(y_test, rbf_pred)
rbf_f1 = f1_score(y_test, rbf_pred, average='weighted')
print('Accuracy (RBF Kernel): ', "%.2f" % (rbf_accuracy*100))
print('F1 (RBF Kernel): ', "%.2f" % (rbf_f1*100))
print(confusion_matrix(y_test, rbf_pred))

Accuracy (RBF Kernel):  93.75
F1 (RBF Kernel):  93.74
[[70  0  4  0]
 [ 0 77  2  9]
 [ 0  0 80  0]
 [ 0  4  1 73]]


Random Forest classsifier

In [ ]:
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier

In [ ]:
classifier = RandomForestClassifier(n_estimators = 1000, criterion = 'entropy', random_state = 42)
classifier.fit(X_train, y_train)

RandomForestClassifier(criterion='entropy', n_estimators=800, random_state=42)

In [ ]:
y_pred = classifier.predict(X_test)

In [ ]:
rf_accuracy = accuracy_score(y_test, y_pred)
rf_f1 = f1_score(y_test, y_pred, average='weighted')
print('Accuracy (Random Forest): ', "%.2f" % (rf_accuracy*100))
print('F1 (Random Forest): ', "%.2f" % (rf_f1*100))
print(confusion_matrix(y_test, y_pred))

Accuracy (Random Forest):  98.75
F1 (Random Forest):  98.75
[[73  0  1  0]
 [ 0 85  0  3]
 [ 0  0 80  0]
 [ 0  0  0 78]]


MultiClass Logistic Regression 

In [ ]:
from sklearn.linear_model import LogisticRegression

In [ ]:
classifier = LogisticRegression(multi_class='auto', solver='sag')
classifier.fit(X_train, y_train)

/usr/local/lib/python3.8/dist-packages/sklearn/linear_model/_sag.py:352: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(


LogisticRegression(solver='sag')

In [ ]:
y_pred = classifier.predict(X_test)

In [ ]:
lr_accuracy = accuracy_score(y_test, y_pred)
lr_f1 = f1_score(y_test, y_pred, average='weighted')
print('Accuracy (Logistic Regression): ', "%.2f" % (lr_accuracy*100))
print('F1 (Logistic Regression): ', "%.2f" % (lr_f1*100))
print(confusion_matrix(y_test, y_pred))

Accuracy (Logistic Regression):  99.38
F1 (Logistic Regression):  99.38
[[73  0  1  0]
 [ 0 87  0  1]
 [ 0  0 80  0]
 [ 0  0  0 78]]
