<a href="https://colab.research.google.com/github/itsmesoumik23/FaceForensics/blob/main/Features_classifier.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Preprocessing

Import Libraries


In [212]:
from sklearn import svm, datasets
import sklearn.model_selection as model_selection
from sklearn.metrics import accuracy_score
from sklearn.metrics import f1_score
from sklearn.metrics import confusion_matrix
import numpy as np
import pandas as pd

Load the Dataset

In [213]:
dataset = pd.read_csv('./Features.csv')
X = dataset.iloc[ : , 2 : ].values
y = dataset.iloc[ : , 0 ].values
print(X)
print(y)

[[0.13151719 0.07062256 0.09944781 ... 0.00222549 0.00553888 0.01158777]
 [0.13184087 0.07120779 0.09940246 ... 0.00186195 0.00496811 0.01130171]
 [0.13314608 0.07112867 0.09793073 ... 0.00228579 0.0057272  0.01090482]
 ...
 [0.10796575 0.08958595 0.09295841 ... 0.07102732 0.06181851 0.17945974]
 [0.10696629 0.08877103 0.09296877 ... 0.07393706 0.06056442 0.18213604]
 [0.11520288 0.08459474 0.09039539 ... 0.070232   0.07304857 0.17970096]]
['Deepfakes' 'Deepfakes' 'Deepfakes' ... 'NeuralTextures' 'NeuralTextures'
 'NeuralTextures']


Split the dataset into training set and test set.

In [214]:
X_train, X_test, y_train, y_test = model_selection.train_test_split(X, y, train_size=0.80, test_size=0.20, random_state=101)

# Support Vector Machine

Polynomial Kernel and RBF Kernel.


In [215]:
rbf = svm.SVC(kernel='rbf', gamma=1, C=1).fit(X_train, y_train)
poly = svm.SVC(kernel='poly', degree=8, C=1).fit(X_train, y_train)

Predict on Test Set.

In [216]:
poly_pred = poly.predict(X_test)
rbf_pred = rbf.predict(X_test)

Outcome from Polynomial Kernel.

In [217]:
poly_accuracy = accuracy_score(y_test, poly_pred)
poly_f1 = f1_score(y_test, poly_pred, average='weighted')
print('Accuracy (Polynomial Kernel): ', "%.2f" % (poly_accuracy*100))
print('F1 (Polynomial Kernel): ', "%.2f" % (poly_f1*100))
print(confusion_matrix(y_test, poly_pred))

Accuracy (Polynomial Kernel):  99.38
F1 (Polynomial Kernel):  99.38
[[80  0  0  0]
 [ 0 78  0  0]
 [ 1  0 87  0]
 [ 0  1  0 73]]


Outcome from RBF Kernel.

In [218]:
rbf_accuracy = accuracy_score(y_test, rbf_pred)
rbf_f1 = f1_score(y_test, rbf_pred, average='weighted')
print('Accuracy (RBF Kernel): ', "%.2f" % (rbf_accuracy*100))
print('F1 (RBF Kernel): ', "%.2f" % (rbf_f1*100))
print(confusion_matrix(y_test, rbf_pred))

Accuracy (RBF Kernel):  72.81
F1 (RBF Kernel):  72.98
[[63  8  7  2]
 [ 2 64  3  9]
 [18 11 58  1]
 [ 0 25  1 48]]


# Random Forest

Importing Libraries

In [219]:
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier

Define the Classifier

In [220]:
classifier = RandomForestClassifier(n_estimators = 1000, criterion = 'entropy', random_state = 42)
classifier.fit(X_train, y_train)

RandomForestClassifier(criterion='entropy', n_estimators=1000, random_state=42)

Predicting Test Set Results

In [221]:
y_pred = classifier.predict(X_test)

Outcome

In [222]:
rf_accuracy = accuracy_score(y_test, y_pred)
rf_f1 = f1_score(y_test, y_pred, average='weighted')
print('Accuracy (Random Forest): ', "%.2f" % (rf_accuracy*100))
print('F1 (Random Forest): ', "%.2f" % (rf_f1*100))
print(confusion_matrix(y_test, y_pred))

Accuracy (Random Forest):  95.31
F1 (Random Forest):  95.33
[[79  1  0  0]
 [ 1 76  0  1]
 [ 5  2 81  0]
 [ 0  5  0 69]]


# MultiClass Logistic Regression

Import Libraries

In [223]:
from sklearn.linear_model import LogisticRegression

Define Classifier.

In [224]:
classifier = LogisticRegression(multi_class='auto', solver='sag')
classifier.fit(X_train, y_train)

/usr/local/lib/python3.8/dist-packages/sklearn/linear_model/_sag.py:352: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(


LogisticRegression(solver='sag')

Predicting Test Set Results.

In [225]:
y_pred = classifier.predict(X_test)

Outcome

In [226]:
lr_accuracy = accuracy_score(y_test, y_pred)
lr_f1 = f1_score(y_test, y_pred, average='weighted')
print('Accuracy (Logistic Regression): ', "%.2f" % (lr_accuracy*100))
print('F1 (Logistic Regression): ', "%.2f" % (lr_f1*100))
print(confusion_matrix(y_test, y_pred))

Accuracy (Logistic Regression):  71.25
F1 (Logistic Regression):  71.25
[[60  5 11  4]
 [ 4 58  6 10]
 [17  6 60  5]
 [ 0 19  5 50]]
